# Generated by Django 5.2.4 on 2025-08-05 07:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_cart_articles_remove_cart_ordered_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.product_image_file_path
            ),
        ),
    ]
